### ISSUE TITLE
Cannot access `EXCLUSIVE_ACCESS` data via API

### ISSUE THREAD

**Issue by exowanderer** [spacetelescope/MAST-API-Notebooks#6]
# Feature Request: API Keys
**Is your feature request related to a problem? Please describe.**
I need to access proprietary data from MAST (i.e. `dataRights == "EXCLUSIVE_ACCESS"`). I am the co-PI of the program and can access the data via MAST Portal; but MAST Portal is broken (for many reasons) and cannot download the data.

MAST Portal suggested that I use the API, which (apparently) does not provide download access for proprietary data.

**Describe the solution you'd like**
I want to provide an `API_KEY` to the `download_products` function inside the astroquery.mast.Observations submodule. I should be given that key by mast.stsci.edu after logging in.

**Describe alternatives you've considered**
I used MAST Portal with cURL and Batch Retrievals; but the website crashed ~10 times while trying that -- I sent a report to archive[at]stsci.edu.

I tried to use archive.stsci.edu (i.e. "MAST Classic"); but that also said "retrieval services are not available".

**Additional context**
The [HST_Data_Access](https://github.com/spacetelescope/MAST-API-Notebooks/blob/master/HST/HST_Data_Access.ipynb) notebook works fine for `dataRights == "PUBLIC"` data; but not for proprietary data.

**Comment by ceb8** [comment]
Hello! Due to some server maintenance being done today there are ongoing intermittent outages for HST download access which I think you are getting caught it. I will let you know when this work is done.

Once HST download access is restored you can follow the directions here: https://astroquery.readthedocs.io/en/latest/mast/mast.html#accessing-proprietary-data to download exclusive access data using Astroquery.

**Comment by ceb8** [comment]
Download access is restored. 

I'm going to close this issue, but please let me know if you continue to have access problems.

**Comment by exowanderer** [comment]
That was perfect! Thank you! No matter what I did, `mast.stsci.edu` just kept crashing -- not errors or warnings. So this was my last known chance. 

I'm glad that API keys do exist. I had no idea :smile:
